name: Bug report
description: Argharghargh !
title: "[Bug 🐛] "
labels: ["Bug 🐛"]
body:
  - type: dropdown
    id: error-type
    attributes:
      label: 'Error type'
      description: What kind of error did you face ?
      options:
        - Error from compiler/makefile
        - Error for socket programming functions
        - Memory leak/dangling pointer/double free
        - Segmentation fault
        - Misc unexpected behaviors
    validations:
      required: true

  - type: textarea
    id: to-recreate
    attributes:
      label: 'Bug process'
      description: The way to make bug in program
      render: Markdown
      placeholder: |
        1.
        2.
        3.
        ...

  - type: textarea
    id: related-code
    attributes:
      label: 'Related codes'
      description: (Auto highlighting in JS)
      render: js

  - type: dropdown
    id: status
    attributes:
      label: 'Error status'
      description: Describe current status of error
      options:
        - Cause is found
        - Solution exists
        - Envr diff with 42-cluster
      multiple: true
