name: Test
description: Creating new feature
title: "[Test] "
labels: ["Test"]
body:
  - type: dropdown
    id: Test-type
    attributes:
      label: "Test type"
      description: What are you going to do for Testing ?
      options:
        - pratice before coding
        - pratice for divided part
        - Testing for functions
        - Testing for running
        - Testing for everything
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: "Implementing process / Goal"
      description: (Auto highlighting in markdown)
      render: Markdown

  - type: textarea
    id: related-code
    attributes:
      label: "Related code"
      description: API or example codes (Auto highlighting in JS)
      render: js

  - type: dropdown
    id: others
    attributes:
      label: "Note"
      description: Additional message
      options:
        - Need to modify existing codes
        - Huge-scale construction is required
      multiple: true